//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class LogAlarmMsg : Message
    {
        public const string k_RosMessageName = "dsr_msgs/LogAlarm";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  log of alarm
        // ____________________________________________________________________________________________
        public int level;
        public int group;
        public int index;
        public string[] param;

        public LogAlarmMsg()
        {
            this.level = 0;
            this.group = 0;
            this.index = 0;
            this.param = new string[3];
        }

        public LogAlarmMsg(int level, int group, int index, string[] param)
        {
            this.level = level;
            this.group = group;
            this.index = index;
            this.param = param;
        }

        public static LogAlarmMsg Deserialize(MessageDeserializer deserializer) => new LogAlarmMsg(deserializer);

        private LogAlarmMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.level);
            deserializer.Read(out this.group);
            deserializer.Read(out this.index);
            deserializer.Read(out this.param, 3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.level);
            serializer.Write(this.group);
            serializer.Write(this.index);
            serializer.Write(this.param);
        }

        public override string ToString()
        {
            return "LogAlarmMsg: " +
            "\nlevel: " + level.ToString() +
            "\ngroup: " + group.ToString() +
            "\nindex: " + index.ToString() +
            "\nparam: " + System.String.Join(", ", param.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
