//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class RobotErrorMsg : Message
    {
        public const string k_RosMessageName = "dsr_msgs/RobotError";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  [ robot error msg ] 
        // ____________________________________________________________________________________________
        public int level;
        //  INFO =1, WARN =2, ERROR =3 
        public int group;
        //  SYSTEM =1, MOTION =2, TP =3, INVERTER =4, SAFETY_CONTROLLER =5   
        public int code;
        //  error code 
        public string msg1;
        //  error msg 1
        public string msg2;
        //  error msg 2
        public string msg3;
        //  error msg 3

        public RobotErrorMsg()
        {
            this.level = 0;
            this.group = 0;
            this.code = 0;
            this.msg1 = "";
            this.msg2 = "";
            this.msg3 = "";
        }

        public RobotErrorMsg(int level, int group, int code, string msg1, string msg2, string msg3)
        {
            this.level = level;
            this.group = group;
            this.code = code;
            this.msg1 = msg1;
            this.msg2 = msg2;
            this.msg3 = msg3;
        }

        public static RobotErrorMsg Deserialize(MessageDeserializer deserializer) => new RobotErrorMsg(deserializer);

        private RobotErrorMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.level);
            deserializer.Read(out this.group);
            deserializer.Read(out this.code);
            deserializer.Read(out this.msg1);
            deserializer.Read(out this.msg2);
            deserializer.Read(out this.msg3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.level);
            serializer.Write(this.group);
            serializer.Write(this.code);
            serializer.Write(this.msg1);
            serializer.Write(this.msg2);
            serializer.Write(this.msg3);
        }

        public override string ToString()
        {
            return "RobotErrorMsg: " +
            "\nlevel: " + level.ToString() +
            "\ngroup: " + group.ToString() +
            "\ncode: " + code.ToString() +
            "\nmsg1: " + msg1.ToString() +
            "\nmsg2: " + msg2.ToString() +
            "\nmsg3: " + msg3.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
