//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class RobotStopMsg : Message
    {
        public const string k_RosMessageName = "dsr_msgs/RobotStop";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  [ robot stop mode ] 
        //  0 : STOP_TYPE_QUICK_STO
        //  1 : STOP_TYPE_QUICK
        //  2 : STOP_TYPE_SLOW
        //  3 : STOP_TYPE_HOLD = STOP_TYPE_EMERGENCY
        // 
        // ____________________________________________________________________________________________
        public int stop_mode;

        public RobotStopMsg()
        {
            this.stop_mode = 0;
        }

        public RobotStopMsg(int stop_mode)
        {
            this.stop_mode = stop_mode;
        }

        public static RobotStopMsg Deserialize(MessageDeserializer deserializer) => new RobotStopMsg(deserializer);

        private RobotStopMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.stop_mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stop_mode);
        }

        public override string ToString()
        {
            return "RobotStopMsg: " +
            "\nstop_mode: " + stop_mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
