//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SpeedJRTStreamMsg : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SpeedJRTStream";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  speedj_rt
        //  
        // ____________________________________________________________________________________________
        public double[] vel;
        //  velocity
        public double[] acc;
        //  acceleration
        public double time;
        //  time

        public SpeedJRTStreamMsg()
        {
            this.vel = new double[6];
            this.acc = new double[6];
            this.time = 0.0;
        }

        public SpeedJRTStreamMsg(double[] vel, double[] acc, double time)
        {
            this.vel = vel;
            this.acc = acc;
            this.time = time;
        }

        public static SpeedJRTStreamMsg Deserialize(MessageDeserializer deserializer) => new SpeedJRTStreamMsg(deserializer);

        private SpeedJRTStreamMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.vel, sizeof(double), 6);
            deserializer.Read(out this.acc, sizeof(double), 6);
            deserializer.Read(out this.time);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.vel);
            serializer.Write(this.acc);
            serializer.Write(this.time);
        }

        public override string ToString()
        {
            return "SpeedJRTStreamMsg: " +
            "\nvel: " + System.String.Join(", ", vel.ToList()) +
            "\nacc: " + System.String.Join(", ", acc.ToList()) +
            "\ntime: " + time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
