//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class AlignAxis1Request : Message
    {
        public const string k_RosMessageName = "dsr_msgs/AlignAxis1";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  align_axis(x1, x2, x3, source_vect, axis, ref)
        // ____________________________________________________________________________________________
        public double[] x1;
        //  task pos(posx)  
        public double[] x2;
        //  task pos(posx)  
        public double[] x3;
        //  task pos(posx)
        public double[] source_vect;
        //  source vector[3]  
        public sbyte axis;
        //  DR_AXIS_X(0), DR_AXIS_Y(1), DR_AXIS_Z(2) 
        public sbyte @ref;
        //  DR_BASE(0), DR_WORLD(2), user coord(101~200)
        //  <ref is only available in M2.40 or later> 

        public AlignAxis1Request()
        {
            this.x1 = new double[6];
            this.x2 = new double[6];
            this.x3 = new double[6];
            this.source_vect = new double[3];
            this.axis = 0;
            this.@ref = 0;
        }

        public AlignAxis1Request(double[] x1, double[] x2, double[] x3, double[] source_vect, sbyte axis, sbyte @ref)
        {
            this.x1 = x1;
            this.x2 = x2;
            this.x3 = x3;
            this.source_vect = source_vect;
            this.axis = axis;
            this.@ref = @ref;
        }

        public static AlignAxis1Request Deserialize(MessageDeserializer deserializer) => new AlignAxis1Request(deserializer);

        private AlignAxis1Request(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x1, sizeof(double), 6);
            deserializer.Read(out this.x2, sizeof(double), 6);
            deserializer.Read(out this.x3, sizeof(double), 6);
            deserializer.Read(out this.source_vect, sizeof(double), 3);
            deserializer.Read(out this.axis);
            deserializer.Read(out this.@ref);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x1);
            serializer.Write(this.x2);
            serializer.Write(this.x3);
            serializer.Write(this.source_vect);
            serializer.Write(this.axis);
            serializer.Write(this.@ref);
        }

        public override string ToString()
        {
            return "AlignAxis1Request: " +
            "\nx1: " + System.String.Join(", ", x1.ToList()) +
            "\nx2: " + System.String.Join(", ", x2.ToList()) +
            "\nx3: " + System.String.Join(", ", x3.ToList()) +
            "\nsource_vect: " + System.String.Join(", ", source_vect.ToList()) +
            "\naxis: " + axis.ToString() +
            "\n@ref: " + @ref.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
