//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class AlterMotionRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/AlterMotion";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  alter_motion  
        //  
        // ____________________________________________________________________________________________
        public double[] pos;
        //  position  

        public AlterMotionRequest()
        {
            this.pos = new double[6];
        }

        public AlterMotionRequest(double[] pos)
        {
            this.pos = pos;
        }

        public static AlterMotionRequest Deserialize(MessageDeserializer deserializer) => new AlterMotionRequest(deserializer);

        private AlterMotionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pos, sizeof(double), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos);
        }

        public override string ToString()
        {
            return "AlterMotionRequest: " +
            "\npos: " + System.String.Join(", ", pos.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
