//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class ChangeOperationSpeedRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/ChangeOperationSpeed";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  change_operation_speed
        // ____________________________________________________________________________________________
        public sbyte speed;
        //  operation speed: (1~100)

        public ChangeOperationSpeedRequest()
        {
            this.speed = 0;
        }

        public ChangeOperationSpeedRequest(sbyte speed)
        {
            this.speed = speed;
        }

        public static ChangeOperationSpeedRequest Deserialize(MessageDeserializer deserializer) => new ChangeOperationSpeedRequest(deserializer);

        private ChangeOperationSpeedRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.speed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.speed);
        }

        public override string ToString()
        {
            return "ChangeOperationSpeedRequest: " +
            "\nspeed: " + speed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
