//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class CheckMotionRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/CheckMotion";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  check_motion
        //  return status of the currently active motion.
        //  Homing is performed by moving to the joint motion to the mechanical or user defined home position.
        //  According to the input parameter [target], it moves to the mechanical home defined in the system or the home set by the user.
        // ____________________________________________________________________________________________

        public CheckMotionRequest()
        {
        }
        public static CheckMotionRequest Deserialize(MessageDeserializer deserializer) => new CheckMotionRequest(deserializer);

        private CheckMotionRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "CheckMotionRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
