//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class ConfigCreateTcpRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/ConfigCreateTcp";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  config_create_tcp  
        //  It is a service for registering and using robot TCP information in advance for safety
        // ____________________________________________________________________________________________
        public string name;
        //  tcp name 
        public double[] pos;
        //  coordinates of the TCP 

        public ConfigCreateTcpRequest()
        {
            this.name = "";
            this.pos = new double[6];
        }

        public ConfigCreateTcpRequest(string name, double[] pos)
        {
            this.name = name;
            this.pos = pos;
        }

        public static ConfigCreateTcpRequest Deserialize(MessageDeserializer deserializer) => new ConfigCreateTcpRequest(deserializer);

        private ConfigCreateTcpRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.pos, sizeof(double), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.pos);
        }

        public override string ToString()
        {
            return "ConfigCreateTcpRequest: " +
            "\nname: " + name.ToString() +
            "\npos: " + System.String.Join(", ", pos.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
