//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class ConfigDeleteModbusRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/ConfigDeleteModbus";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  config_delete_modbus 
        //  It is a service to delete the Modbus I / O signal information registered 
        //  in advance in the robot controller 
        // ____________________________________________________________________________________________
        public string name;
        //  modbus signal symbol 

        public ConfigDeleteModbusRequest()
        {
            this.name = "";
        }

        public ConfigDeleteModbusRequest(string name)
        {
            this.name = name;
        }

        public static ConfigDeleteModbusRequest Deserialize(MessageDeserializer deserializer) => new ConfigDeleteModbusRequest(deserializer);

        private ConfigDeleteModbusRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "ConfigDeleteModbusRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
