//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class ConfigDeleteToolRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/ConfigDeleteTool";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  config_delete_tool  
        //  It is a service to delete tool information registered in advance in the robot controller
        // ____________________________________________________________________________________________
        public string name;
        //  tool name 

        public ConfigDeleteToolRequest()
        {
            this.name = "";
        }

        public ConfigDeleteToolRequest(string name)
        {
            this.name = name;
        }

        public static ConfigDeleteToolRequest Deserialize(MessageDeserializer deserializer) => new ConfigDeleteToolRequest(deserializer);

        private ConfigDeleteToolRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "ConfigDeleteToolRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
