//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class ConfigCreateToolRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/ConfigCreateTool";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  config_create_tool 
        //  It is a service for registering and using robot Tool information in advance for safety 
        // ____________________________________________________________________________________________
        public string name;
        //  tool name 
        public double weight;
        //  tool weight 
        public double[] cog;
        //  Center of gravity
        public double[] inertia;
        //  tool inertia 

        public ConfigCreateToolRequest()
        {
            this.name = "";
            this.weight = 0.0;
            this.cog = new double[3];
            this.inertia = new double[6];
        }

        public ConfigCreateToolRequest(string name, double weight, double[] cog, double[] inertia)
        {
            this.name = name;
            this.weight = weight;
            this.cog = cog;
            this.inertia = inertia;
        }

        public static ConfigCreateToolRequest Deserialize(MessageDeserializer deserializer) => new ConfigCreateToolRequest(deserializer);

        private ConfigCreateToolRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.weight);
            deserializer.Read(out this.cog, sizeof(double), 3);
            deserializer.Read(out this.inertia, sizeof(double), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.weight);
            serializer.Write(this.cog);
            serializer.Write(this.inertia);
        }

        public override string ToString()
        {
            return "ConfigCreateToolRequest: " +
            "\nname: " + name.ToString() +
            "\nweight: " + weight.ToString() +
            "\ncog: " + System.String.Join(", ", cog.ToList()) +
            "\ninertia: " + System.String.Join(", ", inertia.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
