//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class DrlResumeRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/DrlResume";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  drl_script_resume  
        //  It is a service to resume the currently paused DRL program in the robot controller.    
        // ____________________________________________________________________________________________

        public DrlResumeRequest()
        {
        }
        public static DrlResumeRequest Deserialize(MessageDeserializer deserializer) => new DrlResumeRequest(deserializer);

        private DrlResumeRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "DrlResumeRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
