//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class FkinRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/Fkin";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  fkin  
        // ____________________________________________________________________________________________
        public double[] pos;
        //  joint pos(posj)  
        public sbyte @ref;
        // = 0      # DR_BASE(0), DR_WORLD(2)
        //  <ref is only available in M2.40 or later> 

        public FkinRequest()
        {
            this.pos = new double[6];
            this.@ref = 0;
        }

        public FkinRequest(double[] pos, sbyte @ref)
        {
            this.pos = pos;
            this.@ref = @ref;
        }

        public static FkinRequest Deserialize(MessageDeserializer deserializer) => new FkinRequest(deserializer);

        private FkinRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pos, sizeof(double), 6);
            deserializer.Read(out this.@ref);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos);
            serializer.Write(this.@ref);
        }

        public override string ToString()
        {
            return "FkinRequest: " +
            "\npos: " + System.String.Join(", ", pos.ToList()) +
            "\n@ref: " + @ref.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
