//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetCurrentSolutionSpaceResponse : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetCurrentSolutionSpace";
        public override string RosMessageName => k_RosMessageName;

        public sbyte sol_space;
        //  solution space : 0 ~ 7
        public bool success;

        public GetCurrentSolutionSpaceResponse()
        {
            this.sol_space = 0;
            this.success = false;
        }

        public GetCurrentSolutionSpaceResponse(sbyte sol_space, bool success)
        {
            this.sol_space = sol_space;
            this.success = success;
        }

        public static GetCurrentSolutionSpaceResponse Deserialize(MessageDeserializer deserializer) => new GetCurrentSolutionSpaceResponse(deserializer);

        private GetCurrentSolutionSpaceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.sol_space);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sol_space);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "GetCurrentSolutionSpaceResponse: " +
            "\nsol_space: " + sol_space.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
