//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetCurrentToolFlangePosxRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetCurrentToolFlangePosx";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_current_tool_flange_posx()  
        // ____________________________________________________________________________________________
        //  This service returns the pose of the current tool flange based on the ref coordinate. In other words, it means the return to tcp=(0,0,0,0,0,0).
        public sbyte @ref;
        //  DR_BASE(0), DR_WORLD(2)

        public GetCurrentToolFlangePosxRequest()
        {
            this.@ref = 0;
        }

        public GetCurrentToolFlangePosxRequest(sbyte @ref)
        {
            this.@ref = @ref;
        }

        public static GetCurrentToolFlangePosxRequest Deserialize(MessageDeserializer deserializer) => new GetCurrentToolFlangePosxRequest(deserializer);

        private GetCurrentToolFlangePosxRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.@ref);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.@ref);
        }

        public override string ToString()
        {
            return "GetCurrentToolFlangePosxRequest: " +
            "\n@ref: " + @ref.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
