//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetControlSpaceResponse : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetControlSpace";
        public override string RosMessageName => k_RosMessageName;

        public sbyte space;
        //  Control mode : Joint space control(1), Task space control(2)
        public bool success;

        public GetControlSpaceResponse()
        {
            this.space = 0;
            this.success = false;
        }

        public GetControlSpaceResponse(sbyte space, bool success)
        {
            this.space = space;
            this.success = success;
        }

        public static GetControlSpaceResponse Deserialize(MessageDeserializer deserializer) => new GetControlSpaceResponse(deserializer);

        private GetControlSpaceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.space);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.space);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "GetControlSpaceResponse: " +
            "\nspace: " + space.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
