//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetCurrentPosjRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetCurrentPosj";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_current_posj()  
        // ____________________________________________________________________________________________
        //  This service returns the current joint angle.

        public GetCurrentPosjRequest()
        {
        }
        public static GetCurrentPosjRequest Deserialize(MessageDeserializer deserializer) => new GetCurrentPosjRequest(deserializer);

        private GetCurrentPosjRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetCurrentPosjRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
