//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetCtrlBoxAnalogInputResponse : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetCtrlBoxAnalogInput";
        public override string RosMessageName => k_RosMessageName;

        public double value;
        public bool success;

        public GetCtrlBoxAnalogInputResponse()
        {
            this.value = 0.0;
            this.success = false;
        }

        public GetCtrlBoxAnalogInputResponse(double value, bool success)
        {
            this.value = value;
            this.success = success;
        }

        public static GetCtrlBoxAnalogInputResponse Deserialize(MessageDeserializer deserializer) => new GetCtrlBoxAnalogInputResponse(deserializer);

        private GetCtrlBoxAnalogInputResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.value);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.value);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "GetCtrlBoxAnalogInputResponse: " +
            "\nvalue: " + value.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
