//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetCurrentVelxRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetCurrentVelx";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_current_velx(ref)  
        // ____________________________________________________________________________________________
        //  This service returns the current tool velocity based on the ref coordinate.
        public sbyte @ref;
        //  DR_BASE(0), DR_WORLD(2)

        public GetCurrentVelxRequest()
        {
            this.@ref = 0;
        }

        public GetCurrentVelxRequest(sbyte @ref)
        {
            this.@ref = @ref;
        }

        public static GetCurrentVelxRequest Deserialize(MessageDeserializer deserializer) => new GetCurrentVelxRequest(deserializer);

        private GetCurrentVelxRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.@ref);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.@ref);
        }

        public override string ToString()
        {
            return "GetCurrentVelxRequest: " +
            "\n@ref: " + @ref.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
