//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetControlSpaceRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetControlSpace";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_control_space()  
        // ____________________________________________________________________________________________
        //  This service returns the current control space.

        public GetControlSpaceRequest()
        {
        }
        public static GetControlSpaceRequest Deserialize(MessageDeserializer deserializer) => new GetControlSpaceRequest(deserializer);

        private GetControlSpaceRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetControlSpaceRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
