//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetCurrentSolutionSpaceRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetCurrentSolutionSpace";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_current_solution_space
        // ____________________________________________________________________________________________
        //  This service returns the current solution space value.

        public GetCurrentSolutionSpaceRequest()
        {
        }
        public static GetCurrentSolutionSpaceRequest Deserialize(MessageDeserializer deserializer) => new GetCurrentSolutionSpaceRequest(deserializer);

        private GetCurrentSolutionSpaceRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetCurrentSolutionSpaceRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
