//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetControlModeRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetControlMode";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_control_mode()  
        // ____________________________________________________________________________________________
        //  This service returns the current control mode.

        public GetControlModeRequest()
        {
        }
        public static GetControlModeRequest Deserialize(MessageDeserializer deserializer) => new GetControlModeRequest(deserializer);

        private GetControlModeRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetControlModeRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
