//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetControlModeResponse : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetControlMode";
        public override string RosMessageName => k_RosMessageName;

        public sbyte control_mode;
        //  Control mode : Position control mode(3), Torque control mode(4)
        public bool success;

        public GetControlModeResponse()
        {
            this.control_mode = 0;
            this.success = false;
        }

        public GetControlModeResponse(sbyte control_mode, bool success)
        {
            this.control_mode = control_mode;
            this.success = success;
        }

        public static GetControlModeResponse Deserialize(MessageDeserializer deserializer) => new GetControlModeResponse(deserializer);

        private GetControlModeResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.control_mode);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.control_mode);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "GetControlModeResponse: " +
            "\ncontrol_mode: " + control_mode.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
