//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetCurrentVeljRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetCurrentVelj";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_current_velj()  
        // ____________________________________________________________________________________________
        //  This service returns the current target joint velocity. It cannot be used in the movel, movec, movesx, moveb, move_spiral, or move_periodic command.

        public GetCurrentVeljRequest()
        {
        }
        public static GetCurrentVeljRequest Deserialize(MessageDeserializer deserializer) => new GetCurrentVeljRequest(deserializer);

        private GetCurrentVeljRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetCurrentVeljRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
