//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetCtrlBoxDigitalOutputRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetCtrlBoxDigitalOutput";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_digital_output  
        // ____________________________________________________________________________________________
        public sbyte index;
        //  ctrlbox digital output port(1 ~ 16)

        public GetCtrlBoxDigitalOutputRequest()
        {
            this.index = 0;
        }

        public GetCtrlBoxDigitalOutputRequest(sbyte index)
        {
            this.index = index;
        }

        public static GetCtrlBoxDigitalOutputRequest Deserialize(MessageDeserializer deserializer) => new GetCtrlBoxDigitalOutputRequest(deserializer);

        private GetCtrlBoxDigitalOutputRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.index);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.index);
        }

        public override string ToString()
        {
            return "GetCtrlBoxDigitalOutputRequest: " +
            "\nindex: " + index.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
