//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetCtrlBoxDigitalInputRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetCtrlBoxDigitalInput";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_digital_input
        //  This service reads the I/O signals from digital contact points of the controller and reads the digital input contact value.
        // ____________________________________________________________________________________________
        public sbyte index;
        //  Digital Input in Control Box(1 ~ 16) 
        //  <GPIO_CTRLBOX_DIGITAL_INDEX>

        public GetCtrlBoxDigitalInputRequest()
        {
            this.index = 0;
        }

        public GetCtrlBoxDigitalInputRequest(sbyte index)
        {
            this.index = index;
        }

        public static GetCtrlBoxDigitalInputRequest Deserialize(MessageDeserializer deserializer) => new GetCtrlBoxDigitalInputRequest(deserializer);

        private GetCtrlBoxDigitalInputRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.index);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.index);
        }

        public override string ToString()
        {
            return "GetCtrlBoxDigitalInputRequest: " +
            "\nindex: " + index.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
