//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetCurrentToolRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetCurrentTool";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_current_tool  
        //  It is a service to fetch the currently set tool information from the robot controller
        // ____________________________________________________________________________________________

        public GetCurrentToolRequest()
        {
        }
        public static GetCurrentToolRequest Deserialize(MessageDeserializer deserializer) => new GetCurrentToolRequest(deserializer);

        private GetCurrentToolRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetCurrentToolRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
