//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetDesiredPosxRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetDesiredPosx";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_desired_posx(ref)  
        // ____________________________________________________________________________________________
        //  This service returns the target pose of the current tool. The pose is based on the ref coordinate.
        public sbyte @ref;
        // = 0   # DR_BASE(0), DR_WORLD(2), user coord(101~200)
        //  <ref is only available in M2.40 or later> 

        public GetDesiredPosxRequest()
        {
            this.@ref = 0;
        }

        public GetDesiredPosxRequest(sbyte @ref)
        {
            this.@ref = @ref;
        }

        public static GetDesiredPosxRequest Deserialize(MessageDeserializer deserializer) => new GetDesiredPosxRequest(deserializer);

        private GetDesiredPosxRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.@ref);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.@ref);
        }

        public override string ToString()
        {
            return "GetDesiredPosxRequest: " +
            "\n@ref: " + @ref.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
