//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetDesiredVelxRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetDesiredVelx";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_desired_velx(ref)  
        // ____________________________________________________________________________________________
        //  This service returns the target velocity of the current tool based on the ref coordinate. 
        //  It cannot be used in the movej, movejx, or movesj service.
        public sbyte @ref;
        //  DR_BASE(0), DR_WORLD(2)

        public GetDesiredVelxRequest()
        {
            this.@ref = 0;
        }

        public GetDesiredVelxRequest(sbyte @ref)
        {
            this.@ref = @ref;
        }

        public static GetDesiredVelxRequest Deserialize(MessageDeserializer deserializer) => new GetDesiredVelxRequest(deserializer);

        private GetDesiredVelxRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.@ref);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.@ref);
        }

        public override string ToString()
        {
            return "GetDesiredVelxRequest: " +
            "\n@ref: " + @ref.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
