//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetDesiredPosjRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetDesiredPosj";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_desired_posj()  
        // ____________________________________________________________________________________________
        //  This service returns the current target joint angle.
        //  It cannot be used in the movel, movec, movesx, moveb, move_spiral, or move_periodic service.

        public GetDesiredPosjRequest()
        {
        }
        public static GetDesiredPosjRequest Deserialize(MessageDeserializer deserializer) => new GetDesiredPosjRequest(deserializer);

        private GetDesiredPosjRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetDesiredPosjRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
