//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetDrlStateRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetDrlState";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_drl_state
        //  Get DRL Program State
        //  0 : DRL_PROGRAM_STATE_PLAY
        //  1 : DRL_PROGRAM_STATE_STOP
        //  2 : DRL_PROGRAM_STATE_HOLD
        //  3 : DRL_PROGRAM_STATE_LAST
        //  drfl.GetProgramState()
        // ____________________________________________________________________________________________

        public GetDrlStateRequest()
        {
        }
        public static GetDrlStateRequest Deserialize(MessageDeserializer deserializer) => new GetDrlStateRequest(deserializer);

        private GetDrlStateRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetDrlStateRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
