//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetDesiredVeljRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetDesiredVelj";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_desired_velj()  
        // ____________________________________________________________________________________________

        public GetDesiredVeljRequest()
        {
        }
        public static GetDesiredVeljRequest Deserialize(MessageDeserializer deserializer) => new GetDesiredVeljRequest(deserializer);

        private GetDesiredVeljRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetDesiredVeljRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
