//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetDesiredVeljResponse : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetDesiredVelj";
        public override string RosMessageName => k_RosMessageName;

        public double[] joint_vel;
        //  Target joint velocity 
        public bool success;

        public GetDesiredVeljResponse()
        {
            this.joint_vel = new double[6];
            this.success = false;
        }

        public GetDesiredVeljResponse(double[] joint_vel, bool success)
        {
            this.joint_vel = joint_vel;
            this.success = success;
        }

        public static GetDesiredVeljResponse Deserialize(MessageDeserializer deserializer) => new GetDesiredVeljResponse(deserializer);

        private GetDesiredVeljResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_vel, sizeof(double), 6);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joint_vel);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "GetDesiredVeljResponse: " +
            "\njoint_vel: " + System.String.Join(", ", joint_vel.ToList()) +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
