//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetExternalTorqueRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetExternalTorque";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_external_torque()
        //  returns the torque value generated by the external force on each current joint.
        // ____________________________________________________________________________________________
        //  This service returns the torque value generated by the external force on each current joint.

        public GetExternalTorqueRequest()
        {
        }
        public static GetExternalTorqueRequest Deserialize(MessageDeserializer deserializer) => new GetExternalTorqueRequest(deserializer);

        private GetExternalTorqueRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetExternalTorqueRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
