//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetLastAlarmRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetLastAlarm";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_last_alarm
        // ##Struct.LOG_ARARM
        // ____________________________________________________________________________________________

        public GetLastAlarmRequest()
        {
        }
        public static GetLastAlarmRequest Deserialize(MessageDeserializer deserializer) => new GetLastAlarmRequest(deserializer);

        private GetLastAlarmRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetLastAlarmRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
