//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetModbusInputRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetModbusInput";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_modbus_input  
        //  This service reads the signal from the Modbus system.
        // ____________________________________________________________________________________________
        public string name;
        //  modbus signal symbol

        public GetModbusInputRequest()
        {
            this.name = "";
        }

        public GetModbusInputRequest(string name)
        {
            this.name = name;
        }

        public static GetModbusInputRequest Deserialize(MessageDeserializer deserializer) => new GetModbusInputRequest(deserializer);

        private GetModbusInputRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "GetModbusInputRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
