//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetOrientationErrorRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetOrientationError";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_orientation_error  
        // ____________________________________________________________________________________________
        //  This service returns the orientation error value between the arbitrary poses xd and xc of the axis.
        public double[] xd;
        //  task pos(posx)  
        public double[] xc;
        //  task pos(posx)  
        public sbyte axis;
        //  DR_AXIS_X(0), DR_AXIS_Y(1), DR_AXIS_Z(2) 

        public GetOrientationErrorRequest()
        {
            this.xd = new double[6];
            this.xc = new double[6];
            this.axis = 0;
        }

        public GetOrientationErrorRequest(double[] xd, double[] xc, sbyte axis)
        {
            this.xd = xd;
            this.xc = xc;
            this.axis = axis;
        }

        public static GetOrientationErrorRequest Deserialize(MessageDeserializer deserializer) => new GetOrientationErrorRequest(deserializer);

        private GetOrientationErrorRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.xd, sizeof(double), 6);
            deserializer.Read(out this.xc, sizeof(double), 6);
            deserializer.Read(out this.axis);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.xd);
            serializer.Write(this.xc);
            serializer.Write(this.axis);
        }

        public override string ToString()
        {
            return "GetOrientationErrorRequest: " +
            "\nxd: " + System.String.Join(", ", xd.ToList()) +
            "\nxc: " + System.String.Join(", ", xc.ToList()) +
            "\naxis: " + axis.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
