//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetRobotSystemRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetRobotSystem";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_robot_system
        // ____________________________________________________________________________________________

        public GetRobotSystemRequest()
        {
        }
        public static GetRobotSystemRequest Deserialize(MessageDeserializer deserializer) => new GetRobotSystemRequest(deserializer);

        private GetRobotSystemRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetRobotSystemRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
