//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetRobotSpeedModeResponse : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetRobotSpeedMode";
        public override string RosMessageName => k_RosMessageName;

        public sbyte speed_mode;
        //  0 : SPEED_NORMAL_MODE
        //  1 : SPEED_REDUCED_MODE
        public bool success;

        public GetRobotSpeedModeResponse()
        {
            this.speed_mode = 0;
            this.success = false;
        }

        public GetRobotSpeedModeResponse(sbyte speed_mode, bool success)
        {
            this.speed_mode = speed_mode;
            this.success = success;
        }

        public static GetRobotSpeedModeResponse Deserialize(MessageDeserializer deserializer) => new GetRobotSpeedModeResponse(deserializer);

        private GetRobotSpeedModeResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.speed_mode);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.speed_mode);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "GetRobotSpeedModeResponse: " +
            "\nspeed_mode: " + speed_mode.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
