//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetRobotSpeedModeRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetRobotSpeedMode";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_robot_speed_mode
        // ____________________________________________________________________________________________

        public GetRobotSpeedModeRequest()
        {
        }
        public static GetRobotSpeedModeRequest Deserialize(MessageDeserializer deserializer) => new GetRobotSpeedModeRequest(deserializer);

        private GetRobotSpeedModeRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetRobotSpeedModeRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
