//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetRobotStateResponse : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetRobotState";
        public override string RosMessageName => k_RosMessageName;

        public sbyte robot_state;
        //  0 : STATE_INITIALIZING
        //  1 : STATE_STANDBY
        //  2 : STATE_MOVING
        //  3 : STATE_SAFE_OFF
        //  4 : STATE_TEACHING
        //  5 : STATE_SAFE_STOP
        //  6 : STATE_EMERGENCY_STOP:
        //  7 : STATE_HOMMING
        //  8 : STATE_RECOVERY
        //  9 : eSTATE_SAFE_STOP2
        //  10: STATE_SAFE_OFF2
        //  11: STATE_RESERVED1
        //  12: STATE_RESERVED2
        //  13: STATE_RESERVED3
        //  14: STATE_RESERVED4
        //  15: STATE_NOT_READY
        public bool success;

        public GetRobotStateResponse()
        {
            this.robot_state = 0;
            this.success = false;
        }

        public GetRobotStateResponse(sbyte robot_state, bool success)
        {
            this.robot_state = robot_state;
            this.success = success;
        }

        public static GetRobotStateResponse Deserialize(MessageDeserializer deserializer) => new GetRobotStateResponse(deserializer);

        private GetRobotStateResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_state);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_state);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "GetRobotStateResponse: " +
            "\nrobot_state: " + robot_state.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
