//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetRTControlInputDataListRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetRTControlInputDataList";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_rt_control_input_data_list
        // ____________________________________________________________________________________________
        public string version;

        public GetRTControlInputDataListRequest()
        {
            this.version = "";
        }

        public GetRTControlInputDataListRequest(string version)
        {
            this.version = version;
        }

        public static GetRTControlInputDataListRequest Deserialize(MessageDeserializer deserializer) => new GetRTControlInputDataListRequest(deserializer);

        private GetRTControlInputDataListRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.version);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.version);
        }

        public override string ToString()
        {
            return "GetRTControlInputDataListRequest: " +
            "\nversion: " + version.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
