//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetRobotModeRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetRobotMode";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_robot_mode
        //  Return to current robot-mode
        //  0 : ROBOT_MODE_MANUAL
        //  1 : ROBOT_MODE_AUTONOMOUS
        //  2 : ROBOT_MODE_MEASURE
        //  drfl.GetRobotMode()
        // ____________________________________________________________________________________________

        public GetRobotModeRequest()
        {
        }
        public static GetRobotModeRequest Deserialize(MessageDeserializer deserializer) => new GetRobotModeRequest(deserializer);

        private GetRobotModeRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetRobotModeRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
