//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetToolDigitalOutputRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetToolDigitalOutput";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_tool_digital_output  
        //  This service gets the current tool io output status.
        // ____________________________________________________________________________________________
        public sbyte index;
        //  flange digital output port(1 ~ 6)

        public GetToolDigitalOutputRequest()
        {
            this.index = 0;
        }

        public GetToolDigitalOutputRequest(sbyte index)
        {
            this.index = index;
        }

        public static GetToolDigitalOutputRequest Deserialize(MessageDeserializer deserializer) => new GetToolDigitalOutputRequest(deserializer);

        private GetToolDigitalOutputRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.index);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.index);
        }

        public override string ToString()
        {
            return "GetToolDigitalOutputRequest: " +
            "\nindex: " + index.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
