//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetToolForceRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetToolForce";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  get_tool_force(ref)
        //  returns the external force applied to the current tool
        // ____________________________________________________________________________________________
        //  This service returns the external force applied to the current tool based on the ref coordinate. 
        //  The force is based on the base coordinate while the moment is based on the tool coordinate.
        public sbyte @ref;
        //  DR_BASE(0), DR_WORLD(2)

        public GetToolForceRequest()
        {
            this.@ref = 0;
        }

        public GetToolForceRequest(sbyte @ref)
        {
            this.@ref = @ref;
        }

        public static GetToolForceRequest Deserialize(MessageDeserializer deserializer) => new GetToolForceRequest(deserializer);

        private GetToolForceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.@ref);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.@ref);
        }

        public override string ToString()
        {
            return "GetToolForceRequest: " +
            "\n@ref: " + @ref.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
