//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetUserCartCoordResponse : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetUserCartCoord";
        public override string RosMessageName => k_RosMessageName;

        public double[] conv_posx;
        //  task pos(posx)  
        public sbyte @ref;
        //  Reference coordinate of the coordinate to get
        public bool success;

        public GetUserCartCoordResponse()
        {
            this.conv_posx = new double[6];
            this.@ref = 0;
            this.success = false;
        }

        public GetUserCartCoordResponse(double[] conv_posx, sbyte @ref, bool success)
        {
            this.conv_posx = conv_posx;
            this.@ref = @ref;
            this.success = success;
        }

        public static GetUserCartCoordResponse Deserialize(MessageDeserializer deserializer) => new GetUserCartCoordResponse(deserializer);

        private GetUserCartCoordResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.conv_posx, sizeof(double), 6);
            deserializer.Read(out this.@ref);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.conv_posx);
            serializer.Write(this.@ref);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "GetUserCartCoordResponse: " +
            "\nconv_posx: " + System.String.Join(", ", conv_posx.ToList()) +
            "\n@ref: " + @ref.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
