//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class GetWorkpieceWeightResponse : Message
    {
        public const string k_RosMessageName = "dsr_msgs/GetWorkpieceWeight";
        public override string RosMessageName => k_RosMessageName;

        public float weight;
        //  Measured weight, Negative value if error
        public bool success;

        public GetWorkpieceWeightResponse()
        {
            this.weight = 0.0f;
            this.success = false;
        }

        public GetWorkpieceWeightResponse(float weight, bool success)
        {
            this.weight = weight;
            this.success = success;
        }

        public static GetWorkpieceWeightResponse Deserialize(MessageDeserializer deserializer) => new GetWorkpieceWeightResponse(deserializer);

        private GetWorkpieceWeightResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.weight);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.weight);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "GetWorkpieceWeightResponse: " +
            "\nweight: " + weight.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
