//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class IkinExRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/IkinEx";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  ikin_ex  
        // ____________________________________________________________________________________________
        public double[] pos;
        //  task pos(posx)  
        public sbyte sol_space;
        //  solution space : 0 ~ 7
        public sbyte @ref;
        // = 0      # DR_BASE(0), DR_WORLD(2)
        public sbyte ref_pos_opt;
        //   

        public IkinExRequest()
        {
            this.pos = new double[6];
            this.sol_space = 0;
            this.@ref = 0;
            this.ref_pos_opt = 0;
        }

        public IkinExRequest(double[] pos, sbyte sol_space, sbyte @ref, sbyte ref_pos_opt)
        {
            this.pos = pos;
            this.sol_space = sol_space;
            this.@ref = @ref;
            this.ref_pos_opt = ref_pos_opt;
        }

        public static IkinExRequest Deserialize(MessageDeserializer deserializer) => new IkinExRequest(deserializer);

        private IkinExRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pos, sizeof(double), 6);
            deserializer.Read(out this.sol_space);
            deserializer.Read(out this.@ref);
            deserializer.Read(out this.ref_pos_opt);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos);
            serializer.Write(this.sol_space);
            serializer.Write(this.@ref);
            serializer.Write(this.ref_pos_opt);
        }

        public override string ToString()
        {
            return "IkinExRequest: " +
            "\npos: " + System.String.Join(", ", pos.ToList()) +
            "\nsol_space: " + sol_space.ToString() +
            "\n@ref: " + @ref.ToString() +
            "\nref_pos_opt: " + ref_pos_opt.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
