//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class JogMultiRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/JogMulti";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  multi jog speed = (250mm/s x 1.73) x unit vecter x speed [%] 
        // ____________________________________________________________________________________________
        public double[] jog_axis;
        //  unit vecter of Task space [Tx, Ty, Tz, Rx, Ry, Rz] : -1.0 ~ +1.0 
        public sbyte move_reference;
        //  0 : MOVE_REFERENCE_BASE, 1 : MOVE_REFERENCE_TOOL, 2 : MOVE_REFERENCE_WORLD
        public double speed;
        //  jog speed [%]  

        public JogMultiRequest()
        {
            this.jog_axis = new double[6];
            this.move_reference = 0;
            this.speed = 0.0;
        }

        public JogMultiRequest(double[] jog_axis, sbyte move_reference, double speed)
        {
            this.jog_axis = jog_axis;
            this.move_reference = move_reference;
            this.speed = speed;
        }

        public static JogMultiRequest Deserialize(MessageDeserializer deserializer) => new JogMultiRequest(deserializer);

        private JogMultiRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.jog_axis, sizeof(double), 6);
            deserializer.Read(out this.move_reference);
            deserializer.Read(out this.speed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.jog_axis);
            serializer.Write(this.move_reference);
            serializer.Write(this.speed);
        }

        public override string ToString()
        {
            return "JogMultiRequest: " +
            "\njog_axis: " + System.String.Join(", ", jog_axis.ToList()) +
            "\nmove_reference: " + move_reference.ToString() +
            "\nspeed: " + speed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
