//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class JogRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/Jog";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  single jog
        //  single jog speed = (250mm/s) x speed [%] 
        // ____________________________________________________________________________________________
        public sbyte jog_axis;
        //  0 ~ 5 : JOINT 1 ~ 6 
        //  6 ~ 11: TASK 1 ~ 6 (X,Y,Z,rx,ry,rz)
        public sbyte move_reference;
        //  0 : MOVE_REFERENCE_BASE, 1 : MOVE_REFERENCE_TOOL
        public double speed;
        //  jog speed [%] : + forward , 0=stop, - backward  

        public JogRequest()
        {
            this.jog_axis = 0;
            this.move_reference = 0;
            this.speed = 0.0;
        }

        public JogRequest(sbyte jog_axis, sbyte move_reference, double speed)
        {
            this.jog_axis = jog_axis;
            this.move_reference = move_reference;
            this.speed = speed;
        }

        public static JogRequest Deserialize(MessageDeserializer deserializer) => new JogRequest(deserializer);

        private JogRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.jog_axis);
            deserializer.Read(out this.move_reference);
            deserializer.Read(out this.speed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.jog_axis);
            serializer.Write(this.move_reference);
            serializer.Write(this.speed);
        }

        public override string ToString()
        {
            return "JogRequest: " +
            "\njog_axis: " + jog_axis.ToString() +
            "\nmove_reference: " + move_reference.ToString() +
            "\nspeed: " + speed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
