//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class ManageAccessControlRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/ManageAccessControl";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  manage_access_control
        // ____________________________________________________________________________________________
        public sbyte access_control;
        //  0 : MANAGE_ACCESS_CONTROL_FORCE_REQUEST
        //  1 : MANAGE_ACCESS_CONTROL_REQUEST
        //  2 : MANAGE_ACCESS_CONTROL_RESPONSE_YES
        //  3 : MANAGE_ACCESS_CONTROL_RESPONSE_NO

        public ManageAccessControlRequest()
        {
            this.access_control = 0;
        }

        public ManageAccessControlRequest(sbyte access_control)
        {
            this.access_control = access_control;
        }

        public static ManageAccessControlRequest Deserialize(MessageDeserializer deserializer) => new ManageAccessControlRequest(deserializer);

        private ManageAccessControlRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.access_control);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.access_control);
        }

        public override string ToString()
        {
            return "ManageAccessControlRequest: " +
            "\naccess_control: " + access_control.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
