//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class MoveLineRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/MoveLine";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  move_line  
        // ____________________________________________________________________________________________
        public double[] pos;
        //  target  
        public double[] vel;
        //  set velocity: [mm/sec], [deg/sec]
        public double[] acc;
        //  set acceleration: [mm/sec2], [deg/sec2]
        public double time;
        // = 0.0       # Time [sec] 
        public double radius;
        // =0.0      # Radius under blending mode [mm] 
        public sbyte @ref;
        //  DR_BASE(0), DR_TOOL(1), DR_WORLD(2)
        //  <DR_WORLD is only available in M2.40 or later> 
        public sbyte mode;
        // = 0         # DR_MV_MOD_ABS(0), DR_MV_MOD_REL(1) 
        public sbyte blendType;
        // = 0    # BLENDING_SPEED_TYPE_DUPLICATE=0, BLENDING_SPEED_TYPE_OVERRIDE=1
        public sbyte syncType;
        // =0      # SYNC = 0, ASYNC = 1

        public MoveLineRequest()
        {
            this.pos = new double[6];
            this.vel = new double[2];
            this.acc = new double[2];
            this.time = 0.0;
            this.radius = 0.0;
            this.@ref = 0;
            this.mode = 0;
            this.blendType = 0;
            this.syncType = 0;
        }

        public MoveLineRequest(double[] pos, double[] vel, double[] acc, double time, double radius, sbyte @ref, sbyte mode, sbyte blendType, sbyte syncType)
        {
            this.pos = pos;
            this.vel = vel;
            this.acc = acc;
            this.time = time;
            this.radius = radius;
            this.@ref = @ref;
            this.mode = mode;
            this.blendType = blendType;
            this.syncType = syncType;
        }

        public static MoveLineRequest Deserialize(MessageDeserializer deserializer) => new MoveLineRequest(deserializer);

        private MoveLineRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pos, sizeof(double), 6);
            deserializer.Read(out this.vel, sizeof(double), 2);
            deserializer.Read(out this.acc, sizeof(double), 2);
            deserializer.Read(out this.time);
            deserializer.Read(out this.radius);
            deserializer.Read(out this.@ref);
            deserializer.Read(out this.mode);
            deserializer.Read(out this.blendType);
            deserializer.Read(out this.syncType);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos);
            serializer.Write(this.vel);
            serializer.Write(this.acc);
            serializer.Write(this.time);
            serializer.Write(this.radius);
            serializer.Write(this.@ref);
            serializer.Write(this.mode);
            serializer.Write(this.blendType);
            serializer.Write(this.syncType);
        }

        public override string ToString()
        {
            return "MoveLineRequest: " +
            "\npos: " + System.String.Join(", ", pos.ToList()) +
            "\nvel: " + System.String.Join(", ", vel.ToList()) +
            "\nacc: " + System.String.Join(", ", acc.ToList()) +
            "\ntime: " + time.ToString() +
            "\nradius: " + radius.ToString() +
            "\n@ref: " + @ref.ToString() +
            "\nmode: " + mode.ToString() +
            "\nblendType: " + blendType.ToString() +
            "\nsyncType: " + syncType.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
