//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class MovePeriodicRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/MovePeriodic";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  move_periodic  
        // ____________________________________________________________________________________________
        public double[] amp;
        //  Amplitude (motion between -amp and +amp) [mm] or [deg]   
        public double[] periodic;
        //  Period (time for 1 cycle) [sec]
        public double acc;
        //  Acc-, dec- time [sec] 
        public sbyte repeat;
        //  Repetition count 
        public sbyte @ref;
        // = 1        # DR_BASE(0), DR_TOOL(1), DR_WORLD(2)
        //  <DR_WORLD is only available in M2.40 or later 
        public sbyte syncType;
        // =0     # SYNC = 0, ASYNC = 1

        public MovePeriodicRequest()
        {
            this.amp = new double[6];
            this.periodic = new double[6];
            this.acc = 0.0;
            this.repeat = 0;
            this.@ref = 0;
            this.syncType = 0;
        }

        public MovePeriodicRequest(double[] amp, double[] periodic, double acc, sbyte repeat, sbyte @ref, sbyte syncType)
        {
            this.amp = amp;
            this.periodic = periodic;
            this.acc = acc;
            this.repeat = repeat;
            this.@ref = @ref;
            this.syncType = syncType;
        }

        public static MovePeriodicRequest Deserialize(MessageDeserializer deserializer) => new MovePeriodicRequest(deserializer);

        private MovePeriodicRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.amp, sizeof(double), 6);
            deserializer.Read(out this.periodic, sizeof(double), 6);
            deserializer.Read(out this.acc);
            deserializer.Read(out this.repeat);
            deserializer.Read(out this.@ref);
            deserializer.Read(out this.syncType);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.amp);
            serializer.Write(this.periodic);
            serializer.Write(this.acc);
            serializer.Write(this.repeat);
            serializer.Write(this.@ref);
            serializer.Write(this.syncType);
        }

        public override string ToString()
        {
            return "MovePeriodicRequest: " +
            "\namp: " + System.String.Join(", ", amp.ToList()) +
            "\nperiodic: " + System.String.Join(", ", periodic.ToList()) +
            "\nacc: " + acc.ToString() +
            "\nrepeat: " + repeat.ToString() +
            "\n@ref: " + @ref.ToString() +
            "\nsyncType: " + syncType.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
