//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class MoveHomeResponse : Message
    {
        public const string k_RosMessageName = "dsr_msgs/MoveHome";
        public override string RosMessageName => k_RosMessageName;

        public sbyte res;
        //  0=success, otherwise fail 
        public bool success;

        public MoveHomeResponse()
        {
            this.res = 0;
            this.success = false;
        }

        public MoveHomeResponse(sbyte res, bool success)
        {
            this.res = res;
            this.success = success;
        }

        public static MoveHomeResponse Deserialize(MessageDeserializer deserializer) => new MoveHomeResponse(deserializer);

        private MoveHomeResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.res);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.res);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "MoveHomeResponse: " +
            "\nres: " + res.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
