//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class MoveHomeRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/MoveHome";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  move_home
        //  Homing is performed by moving to the joint motion to the mechanical or user defined home position.
        //  According to the input parameter [target], it moves to the mechanical home defined in the system or the home set by the user.
        // ____________________________________________________________________________________________
        public sbyte target;
        //  DR_HOME_TARGET_MECHANIC(0) : Mechanical home, joint angle (0,0,0,0,0,0)
        //  DR_HOME_TARGET_USER(1)     : user home

        public MoveHomeRequest()
        {
            this.target = 0;
        }

        public MoveHomeRequest(sbyte target)
        {
            this.target = target;
        }

        public static MoveHomeRequest Deserialize(MessageDeserializer deserializer) => new MoveHomeRequest(deserializer);

        private MoveHomeRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.target);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target);
        }

        public override string ToString()
        {
            return "MoveHomeRequest: " +
            "\ntarget: " + target.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
