//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class MoveStopRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/MoveStop";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  stop()
        //  인자 설명 추가 필요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        // ____________________________________________________________________________________________
        public int stop_mode;
        //  DR_QSTOP_STO(0) : Quick stop (Stop Category 1 without STO(Safe Torque Off)
        //  DR_QSTOP(1)     : Quick stop (Stop Category 2)
        //  DR_SSTO(2)      : Soft Stop
        //  DR_HOLD(3)      : HOLD stop

        public MoveStopRequest()
        {
            this.stop_mode = 0;
        }

        public MoveStopRequest(int stop_mode)
        {
            this.stop_mode = stop_mode;
        }

        public static MoveStopRequest Deserialize(MessageDeserializer deserializer) => new MoveStopRequest(deserializer);

        private MoveStopRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.stop_mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stop_mode);
        }

        public override string ToString()
        {
            return "MoveStopRequest: " +
            "\nstop_mode: " + stop_mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
