//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class MoveSplineJointRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/MoveSplineJoint";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  move_spline_joint  
        // ##float64[100][6] pos         # target
        // ____________________________________________________________________________________________
        public Std.Float64MultiArrayMsg[] pos;
        //  target [100][6] pos
        public sbyte posCnt;
        //  target cnt 
        public double[] vel;
        //  set joint velocity: [deg/sec]
        public double[] acc;
        //  set joint acceleration: [deg/sec2] 
        public double time;
        // = 0.0                   # Time [sec] 
        public sbyte mode;
        // = 0                     # MOVE_MODE_ABSOLUTE=0, MOVE_MODE_RELATIVE=1 
        public sbyte syncType;
        // =0                  # SYNC = 0, ASYNC = 1

        public MoveSplineJointRequest()
        {
            this.pos = new Std.Float64MultiArrayMsg[0];
            this.posCnt = 0;
            this.vel = new double[6];
            this.acc = new double[6];
            this.time = 0.0;
            this.mode = 0;
            this.syncType = 0;
        }

        public MoveSplineJointRequest(Std.Float64MultiArrayMsg[] pos, sbyte posCnt, double[] vel, double[] acc, double time, sbyte mode, sbyte syncType)
        {
            this.pos = pos;
            this.posCnt = posCnt;
            this.vel = vel;
            this.acc = acc;
            this.time = time;
            this.mode = mode;
            this.syncType = syncType;
        }

        public static MoveSplineJointRequest Deserialize(MessageDeserializer deserializer) => new MoveSplineJointRequest(deserializer);

        private MoveSplineJointRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pos, Std.Float64MultiArrayMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.posCnt);
            deserializer.Read(out this.vel, sizeof(double), 6);
            deserializer.Read(out this.acc, sizeof(double), 6);
            deserializer.Read(out this.time);
            deserializer.Read(out this.mode);
            deserializer.Read(out this.syncType);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.pos);
            serializer.Write(this.pos);
            serializer.Write(this.posCnt);
            serializer.Write(this.vel);
            serializer.Write(this.acc);
            serializer.Write(this.time);
            serializer.Write(this.mode);
            serializer.Write(this.syncType);
        }

        public override string ToString()
        {
            return "MoveSplineJointRequest: " +
            "\npos: " + System.String.Join(", ", pos.ToList()) +
            "\nposCnt: " + posCnt.ToString() +
            "\nvel: " + System.String.Join(", ", vel.ToList()) +
            "\nacc: " + System.String.Join(", ", acc.ToList()) +
            "\ntime: " + time.ToString() +
            "\nmode: " + mode.ToString() +
            "\nsyncType: " + syncType.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
