//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class MoveWaitRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/MoveWait";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  move_wait
        //  This Service sets the waiting time between the previous motion command 
        //  and the motion command in the next line.
        // ____________________________________________________________________________________________

        public MoveWaitRequest()
        {
        }
        public static MoveWaitRequest Deserialize(MessageDeserializer deserializer) => new MoveWaitRequest(deserializer);

        private MoveWaitRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "MoveWaitRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
