//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class OverwriteUserCartCoordResponse : Message
    {
        public const string k_RosMessageName = "dsr_msgs/OverwriteUserCartCoord";
        public override string RosMessageName => k_RosMessageName;

        public sbyte id;
        //  Successful coordinate setting, Set user coordinate ID (101 - 200)
        //  (-1) Failed coordinate setting
        public bool success;

        public OverwriteUserCartCoordResponse()
        {
            this.id = 0;
            this.success = false;
        }

        public OverwriteUserCartCoordResponse(sbyte id, bool success)
        {
            this.id = id;
            this.success = success;
        }

        public static OverwriteUserCartCoordResponse Deserialize(MessageDeserializer deserializer) => new OverwriteUserCartCoordResponse(deserializer);

        private OverwriteUserCartCoordResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "OverwriteUserCartCoordResponse: " +
            "\nid: " + id.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
