//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class ParallelAxis2Request : Message
    {
        public const string k_RosMessageName = "dsr_msgs/ParallelAxis2";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  parallel_axis(vect, axis, ref)  
        // ____________________________________________________________________________________________
        public double[] vect;
        //  vector[3]  
        public sbyte axis;
        //  DR_AXIS_X(0), DR_AXIS_Y(1), DR_AXIS_Z(2) 
        public sbyte @ref;
        // = 0   # DR_BASE(0), DR_WORLD(2), user coord(101~200)
        //  <ref is only available in M2.40 or later> 

        public ParallelAxis2Request()
        {
            this.vect = new double[3];
            this.axis = 0;
            this.@ref = 0;
        }

        public ParallelAxis2Request(double[] vect, sbyte axis, sbyte @ref)
        {
            this.vect = vect;
            this.axis = axis;
            this.@ref = @ref;
        }

        public static ParallelAxis2Request Deserialize(MessageDeserializer deserializer) => new ParallelAxis2Request(deserializer);

        private ParallelAxis2Request(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.vect, sizeof(double), 3);
            deserializer.Read(out this.axis);
            deserializer.Read(out this.@ref);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.vect);
            serializer.Write(this.axis);
            serializer.Write(this.@ref);
        }

        public override string ToString()
        {
            return "ParallelAxis2Request: " +
            "\nvect: " + System.String.Join(", ", vect.ToList()) +
            "\naxis: " + axis.ToString() +
            "\n@ref: " + @ref.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
