//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class ReadDataRTResponse : Message
    {
        public const string k_RosMessageName = "dsr_msgs/ReadDataRT";
        public override string RosMessageName => k_RosMessageName;

        public RobotStateRTMsg data;

        public ReadDataRTResponse()
        {
            this.data = new RobotStateRTMsg();
        }

        public ReadDataRTResponse(RobotStateRTMsg data)
        {
            this.data = data;
        }

        public static ReadDataRTResponse Deserialize(MessageDeserializer deserializer) => new ReadDataRTResponse(deserializer);

        private ReadDataRTResponse(MessageDeserializer deserializer)
        {
            this.data = RobotStateRTMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "ReadDataRTResponse: " +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
