//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class ReleaseProtectiveStopRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/ReleaseProtectiveStop";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  release_protective_stop
        // ____________________________________________________________________________________________
        public sbyte release_mode;
        //  0=RELEASE_MODE_STOP, 1=RELEASE_MODE_RESUME, 2=RELEASE_MODE_RELEASE, 3=RELEASE_MODE_RESET

        public ReleaseProtectiveStopRequest()
        {
            this.release_mode = 0;
        }

        public ReleaseProtectiveStopRequest(sbyte release_mode)
        {
            this.release_mode = release_mode;
        }

        public static ReleaseProtectiveStopRequest Deserialize(MessageDeserializer deserializer) => new ReleaseProtectiveStopRequest(deserializer);

        private ReleaseProtectiveStopRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.release_mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.release_mode);
        }

        public override string ToString()
        {
            return "ReleaseProtectiveStopRequest: " +
            "\nrelease_mode: " + release_mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
