//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class ReleaseForceRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/ReleaseForce";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  release_force  
        // ____________________________________________________________________________________________
        public double time;
        //  0          # Time needed to reduce the force (0 ~ 1.0) 

        public ReleaseForceRequest()
        {
            this.time = 0.0;
        }

        public ReleaseForceRequest(double time)
        {
            this.time = time;
        }

        public static ReleaseForceRequest Deserialize(MessageDeserializer deserializer) => new ReleaseForceRequest(deserializer);

        private ReleaseForceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.time);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.time);
        }

        public override string ToString()
        {
            return "ReleaseForceRequest: " +
            "\ntime: " + time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
