//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class ResetWorkpieceWeightRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/ResetWorkpieceWeight";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  reset_workpiece_weight
        //  Initializes the weight data of the material to initialize the algorithm before measuring the weight of the material.
        //  ____________________________________________________________________________________________

        public ResetWorkpieceWeightRequest()
        {
        }
        public static ResetWorkpieceWeightRequest Deserialize(MessageDeserializer deserializer) => new ResetWorkpieceWeightRequest(deserializer);

        private ResetWorkpieceWeightRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ResetWorkpieceWeightRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
