//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class Robotiq2FCloseRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/Robotiq2FClose";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  robotiq_2f_close
        //  close the virtual robotiq gripper  
        // ____________________________________________________________________________________________
        //  None     

        public Robotiq2FCloseRequest()
        {
        }
        public static Robotiq2FCloseRequest Deserialize(MessageDeserializer deserializer) => new Robotiq2FCloseRequest(deserializer);

        private Robotiq2FCloseRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "Robotiq2FCloseRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
