//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SerialSendDataRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SerialSendData";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  serial_send_data
        //  send byte data to other device 
        //  you can operate the real-robotiq gripper by modbus rtu
        // ____________________________________________________________________________________________
        public string data;

        public SerialSendDataRequest()
        {
            this.data = "";
        }

        public SerialSendDataRequest(string data)
        {
            this.data = data;
        }

        public static SerialSendDataRequest Deserialize(MessageDeserializer deserializer) => new SerialSendDataRequest(deserializer);

        private SerialSendDataRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "SerialSendDataRequest: " +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
