//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SetAccXRTRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SetAccXRT";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  set_accx_rt
        // ____________________________________________________________________________________________
        public double trans;
        public double rotation;

        public SetAccXRTRequest()
        {
            this.trans = 0.0;
            this.rotation = 0.0;
        }

        public SetAccXRTRequest(double trans, double rotation)
        {
            this.trans = trans;
            this.rotation = rotation;
        }

        public static SetAccXRTRequest Deserialize(MessageDeserializer deserializer) => new SetAccXRTRequest(deserializer);

        private SetAccXRTRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.trans);
            deserializer.Read(out this.rotation);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trans);
            serializer.Write(this.rotation);
        }

        public override string ToString()
        {
            return "SetAccXRTRequest: " +
            "\ntrans: " + trans.ToString() +
            "\nrotation: " + rotation.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
