//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SetCtrlBoxDigitalOutputRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SetCtrlBoxDigitalOutput";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  set_digital_output  
        // ____________________________________________________________________________________________
        public sbyte index;
        //  ctrlbox digital output port(1 ~ 16)
        public sbyte value;
        //  0 : ON, 1 : OFF

        public SetCtrlBoxDigitalOutputRequest()
        {
            this.index = 0;
            this.value = 0;
        }

        public SetCtrlBoxDigitalOutputRequest(sbyte index, sbyte value)
        {
            this.index = index;
            this.value = value;
        }

        public static SetCtrlBoxDigitalOutputRequest Deserialize(MessageDeserializer deserializer) => new SetCtrlBoxDigitalOutputRequest(deserializer);

        private SetCtrlBoxDigitalOutputRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.index);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.index);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "SetCtrlBoxDigitalOutputRequest: " +
            "\nindex: " + index.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
