//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SetCtrlBoxAnalogInputTypeRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SetCtrlBoxAnalogInputType";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  set_ctrl_box_analog_input_type  
        // ____________________________________________________________________________________________
        public sbyte channel;
        //  1 = ch1, 2= ch2 
        public sbyte mode;
        //  0 = current, 1 = voltage

        public SetCtrlBoxAnalogInputTypeRequest()
        {
            this.channel = 0;
            this.mode = 0;
        }

        public SetCtrlBoxAnalogInputTypeRequest(sbyte channel, sbyte mode)
        {
            this.channel = channel;
            this.mode = mode;
        }

        public static SetCtrlBoxAnalogInputTypeRequest Deserialize(MessageDeserializer deserializer) => new SetCtrlBoxAnalogInputTypeRequest(deserializer);

        private SetCtrlBoxAnalogInputTypeRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.channel);
            deserializer.Read(out this.mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.channel);
            serializer.Write(this.mode);
        }

        public override string ToString()
        {
            return "SetCtrlBoxAnalogInputTypeRequest: " +
            "\nchannel: " + channel.ToString() +
            "\nmode: " + mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
