//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SetDesiredForceRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SetDesiredForce";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  set_desired_force  
        // ____________________________________________________________________________________________
        public double[] fd;
        //  Three translational target forces + Three rotational target moments
        public sbyte[] dir;
        //  Force control in the corresponding direction if 1, Compliance control in the corresponding direction if 0
        public sbyte @ref;
        //  Reference coordinate of the coordinate to get
        public double time;
        //  0          # Transition time of target force to take effect (0 ~ 1.0 sec)
        public sbyte mod;
        //  DR_FC_MOD_ABS(0): force control with absolute value, 
        //  DR_FC_MOD_REL(1): force control with relative value to initial state (the instance when this function is called) 

        public SetDesiredForceRequest()
        {
            this.fd = new double[6];
            this.dir = new sbyte[6];
            this.@ref = 0;
            this.time = 0.0;
            this.mod = 0;
        }

        public SetDesiredForceRequest(double[] fd, sbyte[] dir, sbyte @ref, double time, sbyte mod)
        {
            this.fd = fd;
            this.dir = dir;
            this.@ref = @ref;
            this.time = time;
            this.mod = mod;
        }

        public static SetDesiredForceRequest Deserialize(MessageDeserializer deserializer) => new SetDesiredForceRequest(deserializer);

        private SetDesiredForceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.fd, sizeof(double), 6);
            deserializer.Read(out this.dir, sizeof(sbyte), 6);
            deserializer.Read(out this.@ref);
            deserializer.Read(out this.time);
            deserializer.Read(out this.mod);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.fd);
            serializer.Write(this.dir);
            serializer.Write(this.@ref);
            serializer.Write(this.time);
            serializer.Write(this.mod);
        }

        public override string ToString()
        {
            return "SetDesiredForceRequest: " +
            "\nfd: " + System.String.Join(", ", fd.ToList()) +
            "\ndir: " + System.String.Join(", ", dir.ToList()) +
            "\n@ref: " + @ref.ToString() +
            "\ntime: " + time.ToString() +
            "\nmod: " + mod.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
