//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SetModbusOutputRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SetModbusOutput";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  set_modbus_output  
        //  This service sends the signal to an external Modbus system. 
        // ____________________________________________________________________________________________
        public string name;
        //  modbus signal symbol
        public int value;
        //  modbus register value

        public SetModbusOutputRequest()
        {
            this.name = "";
            this.value = 0;
        }

        public SetModbusOutputRequest(string name, int value)
        {
            this.name = name;
            this.value = value;
        }

        public static SetModbusOutputRequest Deserialize(MessageDeserializer deserializer) => new SetModbusOutputRequest(deserializer);

        private SetModbusOutputRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "SetModbusOutputRequest: " +
            "\nname: " + name.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
