//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SetRobotControlRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SetRobotControl";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  set_robot_control
        // ____________________________________________________________________________________________
        public sbyte robot_control;
        //  0 : CONTROL_INIT_CONFIG
        //  1 : CONTROL_ENABLE_OPERATION
        //  2 : CONTROL_RESET_SAFET_STOP
        //  3 : CONTROL_RESET_SAFE_STOP = CONTROL_RESET_SAFET_STOP,
        //  4 : CONTROL_RESET_SAFET_OFF,
        //  5 : CONTROL_RESET_SAFE_OFF = CONTROL_RESET_SAFET_OFF,
        //  6 : CONTROL_SERVO_ON = CONTROL_RESET_SAFET_OFF,
        //  7 : CONTROL_RECOVERY_SAFE_STOP,
        //  8 : CONTROL_RECOVERY_SAFE_OFF,
        //  9 : CONTROL_RECOVERY_BACKDRIVE,
        //  10: CONTROL_RESET_RECOVERY,
        //  11: CONTROL_LAST

        public SetRobotControlRequest()
        {
            this.robot_control = 0;
        }

        public SetRobotControlRequest(sbyte robot_control)
        {
            this.robot_control = robot_control;
        }

        public static SetRobotControlRequest Deserialize(MessageDeserializer deserializer) => new SetRobotControlRequest(deserializer);

        private SetRobotControlRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_control);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_control);
        }

        public override string ToString()
        {
            return "SetRobotControlRequest: " +
            "\nrobot_control: " + robot_control.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
