//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SetRefCoordRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SetRefCoord";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  set_ref_coord 
        // ____________________________________________________________________________________________
        public sbyte coord;
        //  DR_BASE(0), DR_TOOL(1), DR_WORLD(2), user coord(101~200)
        //  <DR_WORLD is only available in M2.40 or later> 

        public SetRefCoordRequest()
        {
            this.coord = 0;
        }

        public SetRefCoordRequest(sbyte coord)
        {
            this.coord = coord;
        }

        public static SetRefCoordRequest Deserialize(MessageDeserializer deserializer) => new SetRefCoordRequest(deserializer);

        private SetRefCoordRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.coord);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.coord);
        }

        public override string ToString()
        {
            return "SetRefCoordRequest: " +
            "\ncoord: " + coord.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
