//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SetRobotSystemRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SetRobotSystem";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  set_robot_system
        // ____________________________________________________________________________________________
        public sbyte robot_system;
        //  0 : ROBOT_SYSTEM_REAL, 1 : ROBOT_SYSTEM_VIRTUAL

        public SetRobotSystemRequest()
        {
            this.robot_system = 0;
        }

        public SetRobotSystemRequest(sbyte robot_system)
        {
            this.robot_system = robot_system;
        }

        public static SetRobotSystemRequest Deserialize(MessageDeserializer deserializer) => new SetRobotSystemRequest(deserializer);

        private SetRobotSystemRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_system);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_system);
        }

        public override string ToString()
        {
            return "SetRobotSystemRequest: " +
            "\nrobot_system: " + robot_system.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
