//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SetRobotModeRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SetRobotMode";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  set_robot_mode
        //  Change the robot-mode
        //  0 : ROBOT_MODE_MANUAL
        //  1 : ROBOT_MODE_AUTONOMOUS
        //  2 :ROBOT_MODE_MEASURE
        //  drfl.SetRobotMode()
        // ____________________________________________________________________________________________
        public sbyte robot_mode;
        //  <Robot_Mode>

        public SetRobotModeRequest()
        {
            this.robot_mode = 0;
        }

        public SetRobotModeRequest(sbyte robot_mode)
        {
            this.robot_mode = robot_mode;
        }

        public static SetRobotModeRequest Deserialize(MessageDeserializer deserializer) => new SetRobotModeRequest(deserializer);

        private SetRobotModeRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_mode);
        }

        public override string ToString()
        {
            return "SetRobotModeRequest: " +
            "\nrobot_mode: " + robot_mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
