//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SetRTControlInputRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SetRTControlInput";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  set_rt_control_input
        // ____________________________________________________________________________________________
        public string version;
        public double period;
        public int loss;

        public SetRTControlInputRequest()
        {
            this.version = "";
            this.period = 0.0;
            this.loss = 0;
        }

        public SetRTControlInputRequest(string version, double period, int loss)
        {
            this.version = version;
            this.period = period;
            this.loss = loss;
        }

        public static SetRTControlInputRequest Deserialize(MessageDeserializer deserializer) => new SetRTControlInputRequest(deserializer);

        private SetRTControlInputRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.version);
            deserializer.Read(out this.period);
            deserializer.Read(out this.loss);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.version);
            serializer.Write(this.period);
            serializer.Write(this.loss);
        }

        public override string ToString()
        {
            return "SetRTControlInputRequest: " +
            "\nversion: " + version.ToString() +
            "\nperiod: " + period.ToString() +
            "\nloss: " + loss.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
