//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SetRobotSpeedModeRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SetRobotSpeedMode";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  set_robot_speed_mode
        // ____________________________________________________________________________________________
        public sbyte speed_mode;
        //  0 : SPEED_NORMAL_MODE, 1 : SPEED_REDUCED_MODE

        public SetRobotSpeedModeRequest()
        {
            this.speed_mode = 0;
        }

        public SetRobotSpeedModeRequest(sbyte speed_mode)
        {
            this.speed_mode = speed_mode;
        }

        public static SetRobotSpeedModeRequest Deserialize(MessageDeserializer deserializer) => new SetRobotSpeedModeRequest(deserializer);

        private SetRobotSpeedModeRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.speed_mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.speed_mode);
        }

        public override string ToString()
        {
            return "SetRobotSpeedModeRequest: " +
            "\nspeed_mode: " + speed_mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
