//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SetToolShapeRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SetToolShape";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  set_tool_shape
        //  It is a service to set information about currently installed tool.  
        //  Activates the tool shape information of the entered name among the tool shape information registered in the Teach Pendant
        // ____________________________________________________________________________________________
        public string name;
        //  Tool name registered in the Teach Pendant

        public SetToolShapeRequest()
        {
            this.name = "";
        }

        public SetToolShapeRequest(string name)
        {
            this.name = name;
        }

        public static SetToolShapeRequest Deserialize(MessageDeserializer deserializer) => new SetToolShapeRequest(deserializer);

        private SetToolShapeRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "SetToolShapeRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
