//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SetUserCartCoord2Request : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SetUserCartCoord2";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  set_user_cart_coord(x1, x2, x3, pos, ref)
        // ____________________________________________________________________________________________
        public double[] x1;
        //  task pos(posx)  
        public double[] x2;
        //  task pos(posx)  
        public double[] x3;
        //  task pos(posx)
        public double[] pos;
        //  pos(posx)
        public sbyte @ref;
        //  DR_BASE(0), DR_WORLD(2)
        //  <ref is only available in M2.40 or later> 

        public SetUserCartCoord2Request()
        {
            this.x1 = new double[6];
            this.x2 = new double[6];
            this.x3 = new double[6];
            this.pos = new double[6];
            this.@ref = 0;
        }

        public SetUserCartCoord2Request(double[] x1, double[] x2, double[] x3, double[] pos, sbyte @ref)
        {
            this.x1 = x1;
            this.x2 = x2;
            this.x3 = x3;
            this.pos = pos;
            this.@ref = @ref;
        }

        public static SetUserCartCoord2Request Deserialize(MessageDeserializer deserializer) => new SetUserCartCoord2Request(deserializer);

        private SetUserCartCoord2Request(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x1, sizeof(double), 6);
            deserializer.Read(out this.x2, sizeof(double), 6);
            deserializer.Read(out this.x3, sizeof(double), 6);
            deserializer.Read(out this.pos, sizeof(double), 6);
            deserializer.Read(out this.@ref);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x1);
            serializer.Write(this.x2);
            serializer.Write(this.x3);
            serializer.Write(this.pos);
            serializer.Write(this.@ref);
        }

        public override string ToString()
        {
            return "SetUserCartCoord2Request: " +
            "\nx1: " + System.String.Join(", ", x1.ToList()) +
            "\nx2: " + System.String.Join(", ", x2.ToList()) +
            "\nx3: " + System.String.Join(", ", x3.ToList()) +
            "\npos: " + System.String.Join(", ", pos.ToList()) +
            "\n@ref: " + @ref.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
