//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SetUserCartCoord1Request : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SetUserCartCoord1";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  set_user_cart_coord(pos, ref)   
        // ____________________________________________________________________________________________
        public double[] pos;
        //  task pos(posx)  
        public sbyte @ref;
        //  DR_BASE(0), DR_WORLD(2)
        //  <ref is only available in M2.40 or later> 

        public SetUserCartCoord1Request()
        {
            this.pos = new double[6];
            this.@ref = 0;
        }

        public SetUserCartCoord1Request(double[] pos, sbyte @ref)
        {
            this.pos = pos;
            this.@ref = @ref;
        }

        public static SetUserCartCoord1Request Deserialize(MessageDeserializer deserializer) => new SetUserCartCoord1Request(deserializer);

        private SetUserCartCoord1Request(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pos, sizeof(double), 6);
            deserializer.Read(out this.@ref);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos);
            serializer.Write(this.@ref);
        }

        public override string ToString()
        {
            return "SetUserCartCoord1Request: " +
            "\npos: " + System.String.Join(", ", pos.ToList()) +
            "\n@ref: " + @ref.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
