//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class SetVelXRTRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/SetVelXRT";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  set_velx_rt
        // ____________________________________________________________________________________________
        public double trans;
        public double rotation;

        public SetVelXRTRequest()
        {
            this.trans = 0.0;
            this.rotation = 0.0;
        }

        public SetVelXRTRequest(double trans, double rotation)
        {
            this.trans = trans;
            this.rotation = rotation;
        }

        public static SetVelXRTRequest Deserialize(MessageDeserializer deserializer) => new SetVelXRTRequest(deserializer);

        private SetVelXRTRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.trans);
            deserializer.Read(out this.rotation);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trans);
            serializer.Write(this.rotation);
        }

        public override string ToString()
        {
            return "SetVelXRTRequest: " +
            "\ntrans: " + trans.ToString() +
            "\nrotation: " + rotation.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
