//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class StartRTControlRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/StartRTControl";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  start_rt_control
        // ____________________________________________________________________________________________

        public StartRTControlRequest()
        {
        }
        public static StartRTControlRequest Deserialize(MessageDeserializer deserializer) => new StartRTControlRequest(deserializer);

        private StartRTControlRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "StartRTControlRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
