//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class TaskComplianceCtrlResponse : Message
    {
        public const string k_RosMessageName = "dsr_msgs/TaskComplianceCtrl";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public TaskComplianceCtrlResponse()
        {
            this.success = false;
        }

        public TaskComplianceCtrlResponse(bool success)
        {
            this.success = success;
        }

        public static TaskComplianceCtrlResponse Deserialize(MessageDeserializer deserializer) => new TaskComplianceCtrlResponse(deserializer);

        private TaskComplianceCtrlResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "TaskComplianceCtrlResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
