//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class TransResponse : Message
    {
        public const string k_RosMessageName = "dsr_msgs/Trans";
        public override string RosMessageName => k_RosMessageName;

        public double[] trans_pos;
        //  trans pos(posx) 
        public bool success;

        public TransResponse()
        {
            this.trans_pos = new double[6];
            this.success = false;
        }

        public TransResponse(double[] trans_pos, bool success)
        {
            this.trans_pos = trans_pos;
            this.success = success;
        }

        public static TransResponse Deserialize(MessageDeserializer deserializer) => new TransResponse(deserializer);

        private TransResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.trans_pos, sizeof(double), 6);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trans_pos);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "TransResponse: " +
            "\ntrans_pos: " + System.String.Join(", ", trans_pos.ToList()) +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
