//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dsr
{
    [Serializable]
    public class WriteDataRTRequest : Message
    {
        public const string k_RosMessageName = "dsr_msgs/WriteDataRT";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  write_data_rt
        // ____________________________________________________________________________________________
        public double[] external_force_torque;
        public int external_digital_input;
        public int external_digital_output;
        public double[] external_analog_input;
        public double[] external_analog_output;

        public WriteDataRTRequest()
        {
            this.external_force_torque = new double[6];
            this.external_digital_input = 0;
            this.external_digital_output = 0;
            this.external_analog_input = new double[6];
            this.external_analog_output = new double[6];
        }

        public WriteDataRTRequest(double[] external_force_torque, int external_digital_input, int external_digital_output, double[] external_analog_input, double[] external_analog_output)
        {
            this.external_force_torque = external_force_torque;
            this.external_digital_input = external_digital_input;
            this.external_digital_output = external_digital_output;
            this.external_analog_input = external_analog_input;
            this.external_analog_output = external_analog_output;
        }

        public static WriteDataRTRequest Deserialize(MessageDeserializer deserializer) => new WriteDataRTRequest(deserializer);

        private WriteDataRTRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.external_force_torque, sizeof(double), 6);
            deserializer.Read(out this.external_digital_input);
            deserializer.Read(out this.external_digital_output);
            deserializer.Read(out this.external_analog_input, sizeof(double), 6);
            deserializer.Read(out this.external_analog_output, sizeof(double), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.external_force_torque);
            serializer.Write(this.external_digital_input);
            serializer.Write(this.external_digital_output);
            serializer.Write(this.external_analog_input);
            serializer.Write(this.external_analog_output);
        }

        public override string ToString()
        {
            return "WriteDataRTRequest: " +
            "\nexternal_force_torque: " + System.String.Join(", ", external_force_torque.ToList()) +
            "\nexternal_digital_input: " + external_digital_input.ToString() +
            "\nexternal_digital_output: " + external_digital_output.ToString() +
            "\nexternal_analog_input: " + System.String.Join(", ", external_analog_input.ToList()) +
            "\nexternal_analog_output: " + System.String.Join(", ", external_analog_output.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
